//! Reusable data model for the Ambition-style Lunex cube menu prototype.
//!
//! The renderer in `main.rs` is still a demo, but it now consumes this data
//! model instead of hard-coding each visual panel directly in the draw path.
//! Host games can build these specs from their own inventory, map, quest, or
//! settings resources and then translate `MenuAction` requests back into game
//! events.

use bevy::prelude::{Component, Plugin, Resource};

/// A normalized page-space rectangle.
///
/// Coordinates are percentages in the page's local 2D layout space. `(0, 0)` is
/// the top-left corner and `(100, 100)` is the bottom-right corner.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MenuRect {
    pub x: f32,
    pub y: f32,
    pub w: f32,
    pub h: f32,
}

impl MenuRect {
    pub const fn new(x: f32, y: f32, w: f32, h: f32) -> Self {
        Self { x, y, w, h }
    }
}

/// Renderer-independent color token.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MenuColor {
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
}

impl MenuColor {
    pub const fn rgba(r: f32, g: f32, b: f32, a: f32) -> Self {
        Self { r, g, b, a }
    }
}

/// Text alignment independent of the concrete renderer.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MenuTextAlign {
    Left,
    Center,
    Right,
}

/// Broad semantic class for controls.
///
/// A renderer may style these differently, and a navigation policy may use this
/// to decide whether a control participates in focus, hover, or scroll.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MenuControlKind {
    Tab,
    Slot,
    Item,
    Action,
    OptionToggle,
    OptionChoice,
    MapMarker,
    Scrollbar,
    Decoration,
}

/// A single page node. `Action` is intentionally generic so games can use their
/// own enum instead of stringly typed callbacks.
#[derive(Clone, Debug)]
pub enum MenuNode<Action> {
    Panel {
        rect: MenuRect,
        color: MenuColor,
        action: Option<Action>,
    },
    Text {
        x: f32,
        y: f32,
        size: f32,
        text: String,
        align: MenuTextAlign,
        color: MenuColor,
    },
    Control {
        rect: MenuRect,
        kind: MenuControlKind,
        label: String,
        detail: Option<String>,
        selected: bool,
        important: bool,
        action: Option<Action>,
    },
}

/// Full data description for one visible page/face of the cube menu.
#[derive(Clone, Debug)]
pub struct MenuPageModel<PageId, Action> {
    pub id: PageId,
    pub title: String,
    pub background: MenuColor,
    pub nodes: Vec<MenuNode<Action>>,
}

impl<PageId, Action> MenuPageModel<PageId, Action> {
    pub fn new(id: PageId, title: impl Into<String>, background: MenuColor) -> Self {
        Self {
            id,
            title: title.into(),
            background,
            nodes: Vec::new(),
        }
    }

    pub fn panel(&mut self, rect: MenuRect, color: MenuColor, action: Option<Action>) {
        self.nodes.push(MenuNode::Panel { rect, color, action });
    }

    pub fn text(
        &mut self,
        x: f32,
        y: f32,
        size: f32,
        text: impl Into<String>,
        align: MenuTextAlign,
        color: MenuColor,
    ) {
        self.nodes.push(MenuNode::Text {
            x,
            y,
            size,
            text: text.into(),
            align,
            color,
        });
    }

    pub fn control(
        &mut self,
        rect: MenuRect,
        kind: MenuControlKind,
        label: impl Into<String>,
        detail: Option<String>,
        selected: bool,
        important: bool,
        action: Option<Action>,
    ) {
        self.nodes.push(MenuNode::Control {
            rect,
            kind,
            label: label.into(),
            detail,
            selected,
            important,
            action,
        });
    }
}

/// Host-facing lifecycle/effect hook. The demo queues these events; an Ambition
/// integration can drain the queue to play sfx, pause gameplay, or muffle music.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MenuShellEffect {
    Opening,
    Opened,
    Closing,
    Closed,
    PageChanged,
    Navigate,
    Activate,
    Cancel,
}

/// Queue of shell effects generated by the menu module.
///
/// This intentionally avoids hard-coding audio or music behavior into the UI.
/// A game can map `Opening`/`Closing` to sounds and map `Opened`/`Closed` to
/// music ducking or gameplay mode changes.
#[derive(Resource, Default, Clone, Debug)]
pub struct MenuShellEffects {
    pub pending: Vec<MenuShellEffect>,
}

impl MenuShellEffects {
    pub fn push(&mut self, effect: MenuShellEffect) {
        self.pending.push(effect);
    }

    pub fn drain(&mut self) -> impl Iterator<Item = MenuShellEffect> + '_ {
        self.pending.drain(..)
    }
}

/// Coarse lifecycle phase derived from a shell's openness and target state.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MenuShellPhase {
    Closed,
    Opening,
    Open,
    Closing,
}

/// Configurable touch policy for game-friendly menus.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TouchActivationPolicy {
    ActivateOnFirstTap,
    SelectThenTap,
}


/// Optional plugin marker for host games that want a single import point.
///
/// The prototype renderer still lives in `main.rs`, but these public types are
/// intentionally crate-shaped. A future extraction can move the Lunex renderer,
/// input systems, and shell animation systems behind this plugin without
/// changing the data model below.
pub struct AmbitionInventoryUiPlugin;

impl Plugin for AmbitionInventoryUiPlugin {
    fn build(&self, _app: &mut bevy::prelude::App) {
        // Intentionally empty in this prototype overlay. The reusable API is
        // already available through ECS components/resources and the data model;
        // renderer systems will move here once the demo hardening settles.
    }
}

/// High-level shell animation style.
///
/// Keep the nostalgic OoT-inspired page fold opt-in at the reusable API level.
/// Most games should start with `SmoothScale` and deliberately choose
/// `OotPageFold` when they want the strong N64 pause-menu identity.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum MenuOpenCloseStyle {
    #[default]
    SmoothScale,
    OotPageFold,
}

/// Configuration resource for a reusable menu shell.
///
/// This intentionally avoids audio/music decisions. Instead, use
/// `MenuShellEffects` and let the host game map lifecycle events to SFX,
/// pause-state changes, or music ducking/muffling.
#[derive(Resource, Clone, Debug)]
pub struct MenuShellConfig {
    pub open_close_style: MenuOpenCloseStyle,
    pub touch_policy: TouchActivationPolicy,
    pub page_rotate_speed: f32,
    pub open_close_speed: f32,
}

impl Default for MenuShellConfig {
    fn default() -> Self {
        Self {
            open_close_style: MenuOpenCloseStyle::SmoothScale,
            touch_policy: TouchActivationPolicy::SelectThenTap,
            page_rotate_speed: 5.2,
            open_close_speed: 8.0,
        }
    }
}

/// Marker for the root entity that owns a menu shell / menu room.
#[derive(Component, Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct AmbitionMenuRoot;

/// ECS component attached to a rendered menu page/face.
#[derive(Component, Clone, Debug, Eq, PartialEq)]
pub struct AmbitionMenuPage<PageId> {
    pub id: PageId,
    pub active: bool,
}

/// Stable navigation identity for focusable controls.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Hash)]
pub struct MenuFocusKey {
    pub row: i32,
    pub col: i32,
    pub order: i32,
}

/// ECS component attached to rendered controls.
///
/// The data-driven builder is still the ergonomic API, but controls that make
/// it into the world should carry their semantic action/kind as components so
/// hover, focus, accessibility, and alternative input can be implemented by ECS
/// systems instead of by renderer-private bookkeeping.
#[derive(Component, Clone, Debug, PartialEq)]
pub struct AmbitionMenuControl<Action> {
    pub kind: MenuControlKind,
    pub action: Option<Action>,
    pub focus: MenuFocusKey,
}

/// Runtime visual state for a control.
///
/// This is the part that belongs in ECS. It changes frequently from hover,
/// focus, touch, and gamepad navigation, while the declarative page data can
/// remain stable and data-driven.
#[derive(Component, Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct MenuVisualState {
    pub hovered: bool,
    pub focused: bool,
    pub selected: bool,
    pub pressed: bool,
    pub disabled: bool,
}

/// ECS metadata for a scrollable viewport.
#[derive(Component, Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct MenuScrollPane {
    pub first_visible: usize,
    pub visible_rows: usize,
    pub total_rows: usize,
}
